### ISSUE TITLE
Fails to build `error: variable 'cons_0' set but not used`

### ISSUE THREAD

**Issue by mothran** [rust-fuzz/afl.rs#316]
When building a target project `cargo afl build` on the following setup I get the below error:

```
      stderr: "GNUmakefile.llvm:68: you are using an in-development llvm version - this might break llvm_mode!\nsrc/afl-fuzz-redqueen.c:1603:20: error: variable 'cons_0' set but not used [-Werror,-Wunused-but-set-variable]\n  u8  cons_ff = 0, cons_0 = 0;\n                   ^\n1 error generated.\nmake: *** [GNUmakefile:452: afl-fuzz] Error 1\n",
  }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.12.16/build.rs:72:5
```

* `clang version 15.0.7`
* `LLD 15.0.7`
* `Arch Linux 6.2.9-arch1-1`

**Comment by smoelius** [comment]
To be clear, afl.rs installs fine (i.e., `cargo install afl` completes without error)?

Can you share the project that causes the problem?

**Comment by mothran** [comment]
Yup `cargo install -f afl` work without issue:

```
   Replacing /home/user/.cargo/bin/cargo-afl
    Replaced package `afl v0.12.16` with `afl v0.12.16` (executable `cargo-afl`)
```

This is a brand new project from `cargo new afl-test` the adding:
```toml
[dependencies]
afl = "*"
url = "*"
```

To Cargo.toml and then Using the Url fuzzer from the book here: https://rust-fuzz.github.io/book/afl/tutorial.html

`main.rs`:

```rust
use afl::fuzz;

fn main() {
    fuzz!(|data: &[u8]| {
        if let Ok(s) = std::str::from_utf8(data) {
            let _ = url::Url::parse(&s);
        }
    });
}
```

The only difference from that is I am using a specific version of the rust-toolchain by adding the following file to the crate root: `rust-toolchain.toml`

```toml
[toolchain]
channel = "nightly-2022-10-28"
components = [ "rustfmt", "rust-src" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
```
